# Generated by Django 4.2.3 on 2023-09-30 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppComunidad', '0004_mensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
