# Generated by Django 4.2.3 on 2023-10-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComunidad', '0006_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
