# Generated by Django 4.2.3 on 2023-10-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComunidad', '0007_comentario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatars/'),
        ),
    ]
