# Generated by Django 4.2.3 on 2023-10-02 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppComunidad', '0008_alter_comentario_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='respuesta_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppComunidad.comentario'),
        ),
    ]
