# Generated by Django 4.2.3 on 2023-10-03 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppComunidad', '0010_comentariopregunta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentariopregunta',
            old_name='contenido',
            new_name='contenidop',
        ),
    ]
