# Generated by Django 4.2.3 on 2023-10-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComunidad', '0012_alter_comentario_respuesta_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentariopregunta',
            old_name='respuesta_a',
            new_name='respuesta_b',
        ),
        migrations.AlterField(
            model_name='comentariopregunta',
            name='contenidop',
            field=models.TextField(blank=True),
        ),
    ]
