# Generated by Django 4.2.3 on 2023-10-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensaje', '0003_mensaje_delete_mensajeriass'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='avatar_remitente',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
