# Generated by Django 4.2.3 on 2023-10-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensaje', '0005_historialmensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmensaje',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
