# Generated by Django 4.2.3 on 2023-10-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensaje', '0007_alter_mensaje_remitente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='remitente',
            new_name='emisor',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='timestamp',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='destinatario',
            new_name='receptor',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='avatar_remitente',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='avatar_emisor',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatars/'),
        ),
        migrations.DeleteModel(
            name='HistorialMensaje',
        ),
    ]
