# Generated by Django 4.2.3 on 2023-10-03 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppMensaje', '0008_rename_remitente_mensaje_emisor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='avatar_emisor',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='receptor',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_emisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_emisor', to=settings.AUTH_USER_MODEL)),
                ('usuario_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_receptor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mensaje',
            name='conversacion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='AppMensaje.conversacion'),
        ),
    ]
